### ISSUE TITLE
Sub task: Database spec and schema

### ISSUE THREAD

**Issue by srri-zz** [ubyssey/dispatch#15]
MySQL? MongoDB? 
Research!
- http://docs.mongodb.org/manual/data-modeling/

**Comment by blx** [comment]
http://staltz.com/djangoconfi-mongoengine/ talks about http://mongoengine.org/

**Comment by psiemens** [comment]
I'm throwing in my vote for MySQL. Stable & suitable for our needs (more so than Mongo, IMHO).

**Comment by srri-zz** [comment]
Sounds good, let's do it then.
