### ISSUE TITLE
Bug: no relative date formatting for ajax-loaded articles on a Section page

### ISSUE THREAD

**Issue by blx** [ubyssey/dispatch#215]
Go to [ubyssey.ca/features/](http://ubyssey.ca/features/) and scroll until the first set of ajax-loaded articles loads.

**Date-time looks like this `2015-09-07T13:19:26Z` instead of `Sept. 7, 2015, 1:23 p.m.`**

I think this is rendered in [Section.jsx#66](https://github.com/ubyssey/dispatch/blob/production/dispatch/themes/ubyssey/static/js/src/components/Section.jsx#L66) but idk where the date formatting code is.

**Comment by jordanschalm** [comment]
Also ajax-loaded articles don't show special characters in snippets

**Comment by jordanschalm** [comment]
The rendering code is the same in Section.jsx and in the template HTML files (just { article.published_at }). It looks like published_at gets assigned as a datetime object in [content/models.py](https://github.com/ubyssey/dispatch/blob/production/dispatch/apps/content/models.py#L198). I'm not sure when the datetime object gets converted to a string
