### ISSUE TITLE
Manager build process and dependencies

### ISSUE THREAD

**Issue by blx** [ubyssey/dispatch#226]
**Edit: Tasks as per Peter's comment below**
- [x] jQuery version standardization
- [ ] Get rid of `vendor/` and setup a dependency mgmt system
- [ ] Move manager static files
- [ ] Modify the build process to copy the compiled output to the public dir
- [ ] General build process cleanup (incl. gulpfiles)

---

Public-facing pages load `https://code.jquery.com/jquery-2.1.4.min.js` while the admin pages load `http://localhost:8888/static/manager/js/vendor/jquery.js` which is v1.11.2.

@psiemens is there a grand reasoning to this or can we standardise on 2.x?

jQuery 2.x doesn't run on IE < 9, but that's about it, they're api-compatible I believe. If we want to cater to old IE the frontend might as well be on 1.x too.

**Comment by psiemens** [comment]
Let's stick with 2.x for both. Most of the CSS isn't compatible with earlier versions of IE anyways. Do you mind testing with the latest version and pushing an update?

This reminds me that I'd like to get rid of the vendor/ directory altogether and use either CDN links or Bower to manage standalone dependencies. I also want to move the manager static files into dispatch/apps/manager/static and modify the build process to copy the compiled files to the public directory. It'd also be a good idea to clean up the gulpfile while we're at it.

**Comment by blx** [comment]
I cleaned up the gulpfile and was looking at the rest of the frontend build stuff. Sounds good.

I'll fix the jquery too.

**Comment by blx** [comment]
https://github.com/ubyssey/dispatch/compare/little-refactors

**Comment by psiemens** [comment]
Oh, nice! I can always count on you to make my code better/prettier.

**Comment by blx** [comment]
Thanks, haha it's the least I can do when `psiemens 847 commits / 1,251,955 ++ / 1,215,876 --`.

jQuery 2 appears to be fine on the admin side, but I've discovered that trying to upload an image into an article instantly crashes my entire Chrome with an `NSUnknownKeyException` so, happy Monday to me.

Good news is that this also happens on jquery 1 so we're probably still good to go :~

Do you wanna give image embedding a shot when you can and see if it blows up for you too? In safari I just get nothing, and no console errors.

**Comment by psiemens** [comment]
This is concerning... 

Image embedding is working for me in all browsers. Can you try at ubyssey.ca/admin/ ?

**Comment by blx** [comment]
Yeah that's just bizarre, still the same. It's probably just something wonky on my computer, I'll keep looking into it
