### ISSUE TITLE
Search button does not work on article pages

### ISSUE THREAD

**Issue by tonglil** [ubyssey/dispatch#233]
Pressing the search button while on an article does not show the search input.

Firefox 40.0.3.

**Comment by psiemens** [comment]
Thanks for the tip. Right now it's working for me in all browsers. Are you getting any console errors when you click it?

**Comment by tonglil** [comment]
Ah, hehehe, having uBlock will disable it (I think there may be interaction with ad code).

<img width="1501" alt="screen shot 2015-09-29 at 9 51 56 am" src="https://cloud.githubusercontent.com/assets/3250776/10171596/c28e7368-668f-11e5-9bb0-cf1526e6d996.png">

**Comment by psiemens** [comment]
Oh, weird... Going to look into this.

**Comment by blx** [comment]
Actually I'm seeing this too, adblock is blocking `dfp.js` which defines `refreshAdvertisements()` and so Article.jsx chokes [here](https://github.com/ubyssey/dispatch/blob/develop/dispatch/themes/ubyssey/static/js/src/components/Article.jsx#L12) when it tries to call the ads, so search doesn't end up getting set up.

**Comment by blx** [comment]
Actually it's worse than that because the JS gets far enough to override/disable the link action of the search button, but not far enough to actually make search work.
