### ISSUE TITLE
Automate testing for releases

### ISSUE THREAD

**Issue by srri-zz** [ubyssey/dispatch#24]
We should have all of our tests run on Travis CI before allowing to merge.

**Comment by srri-zz** [comment]
@psiemens @blx thoughts?

**Comment by psiemens** [comment]
I'm down for this. How do you set it up?

**Comment by srri-zz** [comment]
I'll investigate, do we have a common `tests` folder?

**Comment by psiemens** [comment]
Each app has its own tests.py, but I think we could consolidate them if we wanted to.

**Comment by srri-zz** [comment]
Yea I think we should put them all in a tests directory, see how boto has their tests directory structured:
https://github.com/boto/boto/tree/develop

**Comment by srri-zz** [comment]
See: http://docs.travis-ci.com/user/languages/python/ @psiemens

**Comment by srri-zz** [comment]
I can set this up, just need to figure out how are testing is done right now

**Comment by psiemens** [comment]
I played around with putting the tests into one folder, but now I don't think we should do it that way. It seems more logical to have the tests for each app inside their own app instead of spreading things out. You can still call all the tests at once with `manage.py test`

**Comment by psiemens** [comment]
You can also run tests for a specific app like so: `manage.py test appname`. It's pretty slick.

**Comment by srri-zz** [comment]
okay that makes sense with the 'app' logic, if it just were like that for every file it would be messy. let's use travis to test each app

**Comment by srri-zz** [comment]
@psiemens can you add the commands you're using to test here? From start to finish (syncdb, manage.py test app, etc.)

**Comment by psiemens** [comment]
`manage.py syncdb` (only required if database hasn't been created yet)
`manage.py test`

That's all I have to do -- not sure if Travis CI needs more?

**Comment by srri-zz** [comment]
It's okay now, I figured it out. Thanks
