### ISSUE TITLE
Raw HTML isn't rendered inside image captions

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#240]
<img width="566" alt="screen shot 2015-09-29 at 5 24 05 pm" src="https://cloud.githubusercontent.com/assets/2547035/10181599/260215b4-66cf-11e5-8197-d08ac62ca219.png">

**Comment by blx** [comment]
![screen shot 2015-09-30 at 7 55 23 am](https://cloud.githubusercontent.com/assets/887504/10196627/b03760e4-6748-11e5-969b-29a056cd2893.png)
