### ISSUE TITLE
Static pages only load if logged in

### ISSUE THREAD

**Issue by willmcdonald** [ubyssey/dispatch#248]
Volunteer, about, contact, advertise pages return error unless logged in

**Comment by blx** [comment]
Have they been published yet?

**Comment by willmcdonald** [comment]
Good call Ben .... Tried clicking the publish button on those pages, but nothing happens

**Comment by jordanschalm** [comment]
Publish button throws this error
`GET http://ubyssey.ca/api/pages/45/publish/?format=json 404 (NOT FOUND)`
Looks like an issue with the url route for publish

**Comment by blx** [comment]
It looks like `PageViewSet` [here](https://github.com/ubyssey/dispatch/blob/develop/dispatch/apps/api/views.py) needs publish/unpublish methods as in the articleviewset
