### ISSUE TITLE
Dropdown menus in article editor are not dismissed if they are visible when clicked

### ISSUE THREAD

**Issue by jordanschalm** [ubyssey/dispatch#252]

**Comment by jordanschalm** [comment]
This is the behaviour I think the editor should have, @blx @psiemens what do you think?

**Comment by blx** [comment]
Sorry, which dropdown menus are you referring to here?

**Comment by jordanschalm** [comment]
The version dropdown menus in the article editor. Sorry, should have been more clear

**Comment by blx** [comment]
Ah, gotcha! I agree, I would expect dropdown buttons to toggle their menu
