### ISSUE TITLE
Featured image boxes sample from the left, rather than centre, of the image

### ISSUE THREAD

**Issue by jordanschalm** [ubyssey/dispatch#253]
``` html
<div class="featured-image-container">
  <img class="featured">
</div>
```

Page elements of this form sample the image from the left when the image is larger than the confines of the container (72x72px). We would like them to sample from the middle of the image. 

Relevant: http://stackoverflow.com/questions/1344169/center-an-image-in-a-div-too-small-for-it

**Comment by psiemens** [comment]
In this case I think it'd be easiest to make it a background image and use `background-position: center`.
