### ISSUE TITLE
Gulp memory usage

### ISSUE THREAD

**Issue by blx** [ubyssey/dispatch#260]
The admin/manager `gulp watch` task just crashed on me after maybe 15 minutes of watching, with the message

```
<--- Last few GCs --->

  447202 ms: Mark-sweep 1413.0 (1442.1) -> 1413.0 (1442.1) MB, 144.7 / 0 ms [last resort gc].
  447349 ms: Mark-sweep 1413.1 (1442.1) -> 1413.1 (1442.1) MB, 147.3 / 0 ms [allocation failure] [promotion limit reached].
  447351 ms: Scavenge 1413.1 (1442.1) -> 1413.1 (1442.1) MB, 0.8 / 0 ms [allocation failure].
  447493 ms: Mark-sweep 1413.1 (1442.1) -> 1413.1 (1442.1) MB, 142.6 / 0 ms [last resort gc].
  447634 ms: Mark-sweep 1413.1 (1442.1) -> 1413.1 (1442.1) MB, 140.7 / 0 ms [last resort gc].
...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

1.4 GB seems excessive to me, but so does 34 second build times.

This falls under #226 and I'm going to look into streamlining and optimizing the build processes.

Has anyone else had gulp crash?

**Comment by psiemens** [comment]
This happens to me, too. It's something I've been ignoring for a while. I have a feeling `reactify` might be the culprit, but I haven't really had time to look into it.
