### ISSUE TITLE
Posts with long words in headline overlap on mobile section pages

### ISSUE THREAD

**Issue by willmcdonald** [ubyssey/dispatch#263]
![screen shot 2015-10-03 at 4 00 49 pm](https://cloud.githubusercontent.com/assets/10147901/10265506/5f5b84c8-69e8-11e5-83c8-22246113b4e5.png)

**Comment by blx** [comment]
Hmm, that's ugly.

CSS3 has some auto-hyphenation properties, but [support is sketchy right now](https://css-tricks.com/almanac/properties/h/hyphenate/). Chrome in particular is awful at this.

There is [a JS library for this](https://github.com/mnater/hyphenator) but I haven't used it before -- anyone else?

**Comment by psiemens** [comment]
It looks like I forgot to make the section page responsive. My plan was to stack the articles -- should be easy to fix with a media query.

**Comment by jordanschalm** [comment]
Reverts to one article per row on mobile now
