### ISSUE TITLE
Regression tests!

### ISSUE THREAD

**Issue by blx** [ubyssey/dispatch#267]
we're running blind here

**Comment by jordanschalm** [comment]
Amen

**Comment by psiemens** [comment]
pssh whatever

**Comment by psiemens** [comment]
kidding we need tests

**Comment by psiemens** [comment]
@blx @jordanschalm Should we establish a testing policy to follow from now on? I was thinking something along the lines of: 

a) Any new feature must be accompanied by appropriate unit tests before being merged.
b) Any bug fix that modifies previously untested code must be accompanied by unit tests covering that specific portion of code, as well as any larger components it is part of.

The second rule would force us to improve our test coverage while we go back and fix bugs. It doesn't make sense to take the time to understand and improve old code without also taking the time to write tests. 

We can also target a few specific areas that _definitely should_ be tested and make a point of writing those tests first.
