### ISSUE TITLE
Rendering articles fails (shows JSON) when special characters (i.e. em/en dashes, curly quotes) appear within h1-h3, lists

### ISSUE THREAD

**Issue by jordanschalm** [ubyssey/dispatch#280]
Also seems to happen if HTML characters are directly entered into the the editor. See http://ubyssey.ca/api/articles/1794/?format=json

**Comment by psiemens** [comment]
Could it be something caused by our refactor of the embed controllers?

**Comment by jordanschalm** [comment]
It could be... I'm going to investigate this locally and see which bit of code is causing it to revert to JSON

**Comment by blx** [comment]
I know I tested lists locally after that refactor and they worked at that point - hmm.

**Comment by jordanschalm** [comment]
Lists and the food blog jack posted on slack with the HTML star characters are both working fine for me locally

Also both are working on the dev server.

And...both seem to be working in a test article on the live server.

**Comment by jordanschalm** [comment]
Aha! For Jack's article at least, it was the curly quote in "It's About Thai", within an H1 block, that caused rendering to fail

**Comment by psiemens** [comment]
Seriously? What the heck. Nice find

**Comment by blx** [comment]
Are we just missing a `|safe` somewhere?

**Comment by jordanschalm** [comment]
Looks like this issue happens, more generally, when "special" characters are inside things like h1-h3 and lists

**Comment by psiemens** [comment]
The fix ended up being [stupidly simple](https://github.com/ubyssey/dispatch/commit/828ac442615a426b6eda89e78a6acb194a6eed38). We were combining `str` and `unicode` objects, which works _almost_ all the time -- one exception being when you attempt to encode unicode HTML entities.

**Comment by blx** [comment]
Ah, python 2, how I love thee.

Good catch Peter!
