### ISSUE TITLE
Additional ads not loading after first article in continuous article list

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#292]
I'm just about to get off a plane, but I found something that looks promising: https://support.google.com/dfp_premium/answer/4578089?hl=en

I might be able to get to this tonight but feel free to take a crack at it @jordanschalm or @blx. Getting those ad impressions is a priority right now.

**Comment by jordanschalm** [comment]
I'm taking at look at this tonight

**Comment by psiemens** [comment]
@jordanschalm Awesome, thanks
