### ISSUE TITLE
Galleries don't work on full width templates

### ISSUE THREAD

**Issue by willmcdonald** [ubyssey/dispatch#308]
Galleries show up in the post, but don't respond to clicks

**Comment by jordanschalm** [comment]
Looks like this issue is confined to the full-width banner template

**Comment by psiemens** [comment]
Issue moved to [ubyssey/ubyssey-dispatch-theme #6](https://github.com/ubyssey/ubyssey-dispatch-theme/issues/6) via [**ZenHub.io**](https://www.zenhub.io/)
