### ISSUE TITLE
Social buttons don't work on AJAX-loaded articles

### ISSUE THREAD

**Issue by jordanschalm** [ubyssey/dispatch#310]

**Comment by jordanschalm** [comment]
in `static/js/dist/main.js` the click events need to be added to the new social buttons on each article load

**Comment by willmcdonald** [comment]
Facebook button doesn't work in general. Gets error message "App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions."

**Comment by psiemens** [comment]
Just moved the app out of development mode (oops). Can one of you try sharing an article? It works for me regardless because the app is under my FB account.

**Comment by willmcdonald** [comment]
Working for me now. Thanks!

**Comment by psiemens** [comment]
Issue moved to [ubyssey/ubyssey-dispatch-theme #7](https://github.com/ubyssey/ubyssey-dispatch-theme/issues/7) via [**ZenHub.io**](https://www.zenhub.io/)
