### ISSUE TITLE
Automatically add latest ISSUU article link and image to print issue box component

### ISSUE THREAD

**Issue by jordanschalm** [ubyssey/dispatch#347]

**Comment by blx** [comment]
@jordanschalm I'm not sure exactly how you wanted to integrate this, but here is a function that will grab the latest article link and image from issuu: https://github.com/ubyssey/dispatch/compare/enhancement/auto-issuu

We could just have a cron job that runs every few hours to ping issuu and update accordingly if there's a new edition?

**Comment by psiemens** [comment]
Issue moved to [ubyssey/ubyssey-dispatch-theme #8](https://github.com/ubyssey/ubyssey-dispatch-theme/issues/8) via [**ZenHub.io**](https://www.zenhub.io/)
