### ISSUE TITLE
Most Popular This Week Box not updated weekly

### ISSUE THREAD

**Issue by willmcdonald** [ubyssey/dispatch#379]
Stories with most overall views rather than most views for the week appear

**Comment by blx** [comment]
cc @jordanschalm @psiemens 

I think the way dispatch stores views right now is just as a count on each article that gets incremented on every view (`dispatch.apps.content.Publishable.views`) -- we're not storing timestamp info so we can't break it down like that currently.

To get things like "most views for the week" we either have to
- write something to periodically pull this stuff out of google analytics (possibly sketchy) or 
- do something like move the `views` count on `Publishable` to be a `View` model that just has a `timestamp` field plus a FK back to the `Publishable` and then whatever other fields we want to record

**Comment by blx** [comment]
The mechanics [are already in place](https://github.com/ubyssey/dispatch/blob/develop/dispatch/apps/content/models.py#L353) to get the most popular articles _edited_ this week (by total views, but it shouldn't matter on that timescale).

This would mostly work, except eg. if Article X, last edited two weeks ago, was super popular this week it wouldn't get listed.

**Comment by psiemens** [comment]
Issue moved to [ubyssey/ubyssey-dispatch-theme #5](https://github.com/ubyssey/ubyssey-dispatch-theme/issues/5) via [**ZenHub.io**](https://www.zenhub.io/)
