### ISSUE TITLE
Updating Weekend Reading Box

### ISSUE THREAD

**Issue by willmcdonald** [ubyssey/dispatch#394]
When new stories added, the "Weekend Reading" title doesn't show up in the homepage. Tried updating it on the backend, but wouldn't show up on home page unless title changed (I added an extra space after Weekend Reading for a workaround)

**Comment by jordanschalm** [comment]
This is a bigger issue with how updating components is handled on the front-end in general.

**Comment by psiemens** [comment]
Issue moved to [ubyssey/ubyssey-dispatch-theme #3](https://github.com/ubyssey/ubyssey-dispatch-theme/issues/3) via [**ZenHub.io**](https://www.zenhub.io/)
