### ISSUE TITLE
Box ad overlaps banner on short articles

### ISSUE THREAD

**Issue by willmcdonald** [ubyssey/dispatch#396]
![screen shot 2016-02-22 at 10 05 18 pm](https://cloud.githubusercontent.com/assets/10147901/13243099/97a422da-d9b0-11e5-90ea-4b38b9a3d411.png)

**Comment by psiemens** [comment]
Issue moved to [ubyssey/ubyssey-dispatch-theme #1](https://github.com/ubyssey/ubyssey-dispatch-theme/issues/1) via [**ZenHub.io**](https://www.zenhub.io/)
