### ISSUE TITLE
Padding on mobile recent articles

### ISSUE THREAD

**Issue by willmcdonald** [ubyssey/dispatch#400]
![screenshot_20160225-124217](https://cloud.githubusercontent.com/assets/10147901/13335716/3fce612e-dbc7-11e5-8502-d0f7b2869ac7.png)

**Comment by psiemens** [comment]
Issue moved to [ubyssey/ubyssey-dispatch-theme #2](https://github.com/ubyssey/ubyssey-dispatch-theme/issues/2) via [**ZenHub.io**](https://www.zenhub.io/)
