### ISSUE TITLE
Add support for polls

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#433]
We want the ability to embed simple polls into articles.

**Comment by i-ron-y** [comment]
Hey, decided to try to work on this one - right now you can insert a poll embed into the article editor in Dispatch, and a poll shows up in the article (with the question, and radio buttons with the choices underneath e question). However, I haven't implemented a way to submit your vote yet, nor the results view for people who have already voted.

I've pushed my changes to these branches, in dispatch and ubyssey.ca respectively:
[433-article-poll-embed (dispatch)](https://github.com/ubyssey/dispatch/tree/433-article-poll-embed)
[433-article-poll-embed (ubyssey.ca)](https://github.com/ubyssey/ubyssey.ca/tree/433-article-poll-embed)

Any pointers for the work ahead?

**Comment by JimFung** [comment]
FYI, Django's "hello world" app is a polls webapp. 
https://docs.djangoproject.com/en/2.0/intro/tutorial01/

**Comment by Rowansdabomb** [comment]
Jamie and I are jumping in on this

**Comment by i-ron-y** [comment]
Go right ahead! I’ve been working solely on the mobile app redesign prototype and everything else has been put on the backburner for the time being, whoops.

**Comment by JamieRL** [comment]
added in PR #803
