### ISSUE TITLE
Ubyssey theme development

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#46]
We need to develop a Dispatch theme for the new Ubyssey website. Design will mainly be based off of our existing mockups, but there is still some design work to be done. I'll put design tasks in a separate epic. 

The development of this theme will consist of both front-end and back-end jobs. Coordinating the work might be a little tricky, but right now I see there being 3 main jobs:
- developing back-end views for each type of page request
- building HTML & CSS templates for each page type
- Javascript development

As of now, here are the page templates that have to be built (mostly HTML + CSS):
- Homepage #48
- Article (single) #50
- Article (continuous) #50 
- Section #49
- Static content (about, contact, legal, etc) #51
- Author bio #52
- Blog home #53 
- Blog post #53
- Video home #54
- Video single #54

Additional components (most of these require some JS):
- Continuous article loading #55 
- Comments bar (will likely use Facebook API) #56
- Photo gallery overlay #57
- Video overlay #58
- Spotlight search #59
- Breaking news updates #60
- Live Twitter feed (via Twitter API) #61
- Sports scores + stats  #62

I'll outline all of these components in more detail in the wiki. Comment and let me know what you might be interested in working on!

**Comment by blx** [comment]
I wanna tackle the Spotlight search #59, I can look at the other streaming stuff too like #61 twitter and #60 breaking news listener.
