### ISSUE TITLE
Write unit tests for Topics and Tags endpoints

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#490]
See https://github.com/ubyssey/dispatch/blob/develop/dispatch/tests/test_api_articles.py for example of API unit tests

**Comment by seongchanlee** [comment]
@psiemens been working to fix this error, found a weird part in the code. 

In view.py, line 168 (located at /apps/api/):
`instance = Tag.objects.get(name=request.data.get('name'))`

Seems like this line of code tries to get the name field in data. It works fine when the payload data contains the name field, but throws error when I try to set payload with either None or a data without name field. Perhaps there is an uncaught exception here?

Seems like topic section is having same issue (line 195):
`instance = Topic.objects.get(name=request.data.get('name'))`

**Comment by seongchanlee** [comment]
It goes same for topic.
