### ISSUE TITLE
Write unit tests for Pages endpoints

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#499]
We need to add a test suite to cover the `api/pages/` endpoint.

You can use this file as an example for how to structure the tests: https://github.com/ubyssey/dispatch/blob/develop/dispatch/tests/test_api_articles.py

The `api/pages/` endpoint supports the following methods:

```py
# List all pages
GET api/pages/

# Retrieve a specific page
GET api/pages/{page_id}/

# Create a new page
POST api/pages/

# Update an existing page
PATCH api/pages/{page_id}/

# Delete a page
DELETE api/pages/{page_id}/
```

When making a `POST` or `PATCH` request, the request body should look something like this:

```json
{
  "title": "Test Page",
  "slug": "test-page",
  "snippet": "This is a test snippet",
  "content": [
    {
      "type": "paragraph",
      "data": "This is some paragraph text"
    },
    {
      "type": "paragraph",
      "data": "This is another paragraph"
    }
  ]
}
```

Here are the test cases we should cover (if you think of more, please add them!):

- Attempting to create a page while unauthorized should result in 401
- Attempting to delete a page while unauthorized should result in 401
- Attempting to create a page without any of the required fields (title, slug, content) should result in 400
- Attempting to create a page with an empty request (`data=None or data={}`) should result in 400
- Should be able to create a page 
- Should be able to update the basic fields of a page (title, slug, snippet)
- Should be able to update the content of a page
- Should be able to delete an existing page

**Comment by Axel-Jacobsen** [comment]
This one is done, can we take it off the issues?

**Comment by psiemens** [comment]
Yep, I'll move it to DONE
