### ISSUE TITLE
Person API unit tests

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#515]
We need to add tests for the `api/people` routes.

A "person" in Dispatch can be an author, photographer, admin user, or all three. The model itself is fairly simple and contains the following fields:

```py
full_name           # StringField - the person's full name
is_admin            # BooleanField- indicates if this person is an admin (probably going to be removed)
image               # ImageField - optional profile image
slug                # SlugField - person's URL slug, e.g. "peter-siemens"
description         # StringField - used for author bios
```

The Person model is located in `dispatch.apps.core.models`

Take a look at some of the other test files for examples of how to structure your tests: https://github.com/ubyssey/dispatch/tree/develop/dispatch/tests

I'll let you come up with the test cases on your own -- try to think of any edge cases that may occur (for example, what should happen when you try to add a slug that already exists?)

**Comment by arashout** [comment]
What should happen when a slug already exits?
Should we be able to create the person but with a slightly different slug?

If I'm not mistaken it looks like in the person model all the fields can be left blank, which means it is very likely to have a repeated "blank" slug?

Is this correct?
