### ISSUE TITLE
Implement event submission form

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#558]
We need to add a public user-facing form that people can use to submit events to our platform. We should be able to implement this entirely with Django's built-in form utilities. 

To start, you'll want to add three new files to the `dispatch/apps/events` directory: `views.py`, `forms.py` and `urls.py`.

You'll then want to update `dispatch/urls.py` to include the events URLs (similar to what's being done for the API urls).

In the `events/urls.py` file, create a new URL (maybe "submit"?) that connects to a submit view defined in `views.py`

You'll also want to add a new directory `dispatch/apps/events/templates` that contains a single template named "submit.html". You'll use this later to render the form layout.

Read through Django's documentation on forms for a good starting place: https://docs.djangoproject.com/en/1.11/topics/forms/

**Comment by Axel-Jacobsen** [comment]
I'll move this one over to review once all of the event form stuff is done
