### ISSUE TITLE
Download and save Facebook images to our server

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#561]
When an event is submitted from a Facebook URL, instead of hotlinking directly to Facebook image URL upon saving, we should download the image and save it to our server. This allows us to control caching, image optimisation, and also prevents any broken links from occurring. Furthermore, it also provides consistency between user-uploaded images and Facebook images by making sure they are saved and accessed in the same way.

To achieve this, we'll have to modify the way the event submission form works:

- An additional **hidden** field should be added to the Event form, called `facebook_image_url`. This field will not be editable by the user but will be pre-populated after data is fetched from the Facebook API.
- If an image is retrieved from Facebook, the image upload field should be hidden and replaced with a small preview of the Facebook image. This preview can be generated by simply adding an `<img>` tag that links to the URL provided by the Facebook API. If the user wishes to replace the Facebook image, they can click "Upload image", which unhides the image upload field.
- When performing an update, the form should first check to see if an image has been passed via the image upload field. If this is the case, that image should be processed and saved to the event model as it normally would
- If no image is passed via the upload field, check to see if `facebook_image_url` contains a value. If this is the case, make a request to fetch the image and save it to our server/database (e.g. https://stackoverflow.com/a/1309682)
- If both fields are empty, assume that no image was provided

- EDIT: If the user has used the Facebook functionality to get a facebook picture, but then chooses a user uploaded picture, they should still be able to revert back to the facebook picture

**Comment by Axel-Jacobsen** [comment]
I've gotten all of this except for the changing of photos displayed. I am using some JQuery code to display user uploaded images (i.e. not facebook): 

Here is the HTML
`<div class="fieldWrapper">
    {{ form.image.errors }}
    <label for="{{ form.image.id_for_label }}">Image for the Event:</label>
    <input type='file' onchange="upload_img(this);" />
    <img id="img_id" src="{{ form.image.value }}" alt="User uploaded image" />
  </div>`

and here is the JQuery
`<script type="text/javascript">

  function upload_img(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#img_id').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
  }
</script>
`

Would I be able to get guidance on changing the displayed photo from the facebook image to user uploaded image, and for saving the user uploaded image?

Thanks!
