### ISSUE TITLE
Save submitted events with is_submission flag

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#562]
- [x] Add an additional `BooleanField` to the `Event` model named `is_submission` that indicates whether the event is a submission
- [x] When creating an event via the submission form, `is_submission` should be `True`
- [x] By default, API listing (`GET api/events/`) should not return events with `is_submission=True`
- [x] If a request is made to `api/events/?pending=1`, return only events with `is_submission=True`

**Comment by Axel-Jacobsen** [comment]
"By default, API listing (GET api/events/) should not return events with is_submission=True" - Where can I find the file that controls this / could you point me in the direction of documentation for this? Thanks

**Comment by psiemens** [comment]
@Axel-Jacobsen 

You'll only want to show submitted events if the following two conditions are true:

- The current user is authenticated (`self.request.user.is_authenticated()`)
- The `pending=1` flag is included in the URL (`self.request.query_params.get('pending')`)

You can add these checks in the [get_queryset()](https://github.com/ubyssey/dispatch/blob/develop/dispatch/apps/api/views.py#L403-L414) method and filter the queryset accordingly
