### ISSUE TITLE
Add is_published field to Event model

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#566]
In order to distinguish between published and unpublished events, an `is_published` boolean field should be added to the event model. It's default value should be false, as all new events are treated as drafts.

After making this change, the API should be updated so that unpublished events (`is_published=False`) are only displayed to authenticated users. This can be done by adding the `DispatchPublishableMixin` to the `EventViewSet` and adding [this line](https://github.com/ubyssey/dispatch/blob/develop/dispatch/apps/api/views.py#L58) to the `get_queryset()` method. The `get_publishable_queryset()` method automatically checks for the right permissions and filters the queryset if needed.

- [x] Update Event model with `is_published` boolean field
- [x] Update EventViewSet to filter unpublished events for unauthenticated users
- [x] Add tests (make sure unauthenticated users can't see unpublished events)

**Comment by Axel-Jacobsen** [comment]
This is the code I wrote to filter the `is_submitted` query filtering:

```def get_queryset(self):

        # Only authenticated users can see submission events
        if self.request.user.is_authenticated():
            queryset = Event.objects.all()
        else:
            queryset = Event.objects.filter(is_submission=False, is_published=True)
        ...
```

Can I do this instead of calling the `get_publishable_queryset()` method?

**Comment by psiemens** [comment]
@Axel-Jacobsen Yep, that works!
