### ISSUE TITLE
Extend widget class to support custom context

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#567]
As of now, the only data that widgets are capable of rendering is that which comes from their defined fields. After thinking about how to best implement the event widgets, I realized that it would be useful to allow for additional data (not from widget fields) to be passed to a widget template. 

For example, I would like to build a widget that automatically fetches 10 upcoming events and renders them in a list. Our current design allows us to define a widget that displays 10 events, but each of those events would have to be picked manually. To get around this, we should extend the widget functionality to allow us to write a bit of code that will fetch 10 events from the database and pass them to the template.

Here's how I imagine it looking:

```python

from dispatch.apps.events.models import Event
from dispatch.theme.widgets import Widget
from dispatch.theme.fields import EventField

def EventsWidget(Widget):

    id = 'upcoming-events-widget'
    title = 'Upcoming events widget'
    template = 'widgets/upcoming-events.html'

    featured_event = EventField('Featured event') # field to display a featured event

    def context(self, data):
        """
        This is an optional method that can be defined on any widget. 
        It simply allows you to add additional data to the template context before rendering. 
        The output of this function is what is passed to the template for rendering.
        """

        # The `data` argument is a dictionary containing data from the event fields. 

        # Additional data fields can be added before returning the final context
        data.upcoming = Event.objects.filter(is_published=True).order_by('-start_time')

        return data
```

- [x] Add support for optional `context()` method on widget classes. Its default implementation should not change the data
- [x] Add tests to make sure `context()` method works as expected

**Comment by Axel-Jacobsen** [comment]
Should I modify the `render` method to take in data from `context` if chosen? I am thinking 
```
def render(self, data=self.prepare_data()):
        """Renders the widget as HTML"""

        template = loader.get_template(self.template)
        return template.render(data)
```
Where we can pass render as `render(context(data))` Thoughts?
