### ISSUE TITLE
Separate panel for pending events

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#568]
A separate panel/page should be added to the events section of the manager to provide an interface for approving pending events. This page should show a list of events that have `is_submission=True` by using the `pending=1` flag in the API call (see #562). After clicking on an event, the user should be taken to a page that displays the event information along with an "Approve" and "Disapprove" button. Clicking "Approve" should update the `is_submission` flag via an API call and then redirect the user back to the pending events page. Clicking the "Disapprove" button should delete the event and return the user to the pending events page.

**Comment by joncppl** [comment]
I made the interface for this use a tiles for each event, all viewed on the same page
Each tile has approve/edit/disapprove buttons. (edit links to normal edit page)
approve updates is_submission, disapprove deletes. Either will cause the tile to animate/ fade-out.

This way a user can view many pending events at once, without having to navigate to different pages.
For example, it would make rejecting a bulk of spammy events very fast.
