### ISSUE TITLE
Submitted events should allow the submitter to give contact info

### ISSUE THREAD

**Issue by joncppl** [ubyssey/dispatch#570]
For instance, a backend user auditing submitted events might need to contact the submitter in order to determine the validity of the event, correctness of the information, etc.

Suggest adding to the model: 
- submitter_email
- submitter_phone

**Comment by psiemens** [comment]
Good idea -- I'll move this into the TODO column.

@Axel-Jacobsen can you add these fields to the event form?

**Comment by Axel-Jacobsen** [comment]
For Sure!

**Comment by Axel-Jacobsen** [comment]
Do we move each issue into the "Review" column once all the tests etc are complete for the issue, as well as the issue itself?
