### ISSUE TITLE
Create dummy class for Facebook API tests

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#571]
In order to test the portions of our application that use the Facebook API, it looks like the best approach is to avoid making actual API calls and instead return hard-coded copies of the responses. The rationale behind this is that our unit tests are really only meant to test *our* code, and therefor we should simply assume that external integrations are working properly.

Here's what I'm thinking:

Add an optional argument [here](https://github.com/ubyssey/dispatch/blob/Event-forms-etc/dispatch/apps/events/facebook.py#L10-L13) that allows you to specify a custom `Facebook` API class. The default value can just be the normal [Facebook](https://github.com/ubyssey/dispatch/blob/Event-forms-etc/dispatch/vendor/apis.py#L6) class, but for our tests we'll pass in `FacebookTest` instead.

`FacebookTest` will define the same methods as `Facebook` (e.g. `get_event`), but will simply return JSON directly instead of making an API call. For example, the `get_event` method might look like this:

```py

# constant that holds dummy event data
EVENTS = {
    17: {
        'title': 'this is a title',
        'description': 'this is a description',
        ...
    }
}

fb.get_event(17) # returns event 17 from above
```

You can put the `FacebookTest` class inside `dispatch/tests/apis.py`

**Comment by Axel-Jacobsen** [comment]
> You can put the FacebookTest class inside dispatch/tests/apis.py

maybe you meant dispatch/vendors/apis.py, with the original `Facebook` class? Or should I make a new folder in dispatch/tests/apis.py?

**Comment by psiemens** [comment]
@Axel-Jacobsen I think it makes more sense to keep it with the test code and put it in `dispatch/tests/apis.py`. That file doesn't exist set so you'd have to create it

**Comment by Axel-Jacobsen** [comment]
@psiemens Sounds good!
