### ISSUE TITLE
Allow creation of topics/tags from the article page

### ISSUE THREAD

**Issue by joncppl** [ubyssey/dispatch#576]
It seems like it may be tedious to have to switch to the tags/topics page, potentially create multiple tags, etc. 
An author may inadvertently navigate to the tags page and lose changes in the article,

Therefore it may be nice to have a quick way to make new tags/topics.
For example, the search bar in the selection dropdown can double as name entry with a "new" button.

**Comment by psiemens** [comment]
Great idea. This was something I wanted to implement eventually, but it'd be awesome to have it for our initial launch.
