### ISSUE TITLE
Event calendar page

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#585]
Create a landing page (dedicated section of our website) that displays all current and upcoming events. Should be filterable by category

**Comment by joncppl** [comment]
This would entail a django template `dispatch\dispatch\apps\frontend\themes\default\templates` and a corresponding view and corresponding view&url, correct?

**Comment by psiemens** [comment]
@joncppl Yep! Eventually we'll move the template to `ubyssey-dispatch-theme`, but you can develop it in this repo for now
