### ISSUE TITLE
Events "forget" their image if it's not reuploaded in a patch request

### ISSUE THREAD

**Issue by joncppl** [ubyssey/dispatch#598]
I was going to just fix this, but a test (test_api_events.test_delete_image) seems to enforcing it.

Not sure what the intended behaviour should be, but I definitely think retaining the image should be prioritized over being able to delete it.

**Comment by Axel-Jacobsen** [comment]
Right, I think it makes sense for the Event to retain its image- I can take care of this if thats ok

**Comment by joncppl** [comment]
Fixed in front end by not sending a null value for the image field
