### ISSUE TITLE
Delete buttons in dispatch should ask for confirmation

### ISSUE THREAD

**Issue by joncppl** [ubyssey/dispatch#600]
This had crossed my mind once or twice, and then Axel brought it to my attention again yesterday.

All across dispatch delete buttons work with a single click, deleting entries with no confirmation.

I suggest a DeleteButton component, that takes the delete method as a prop, but instead of running it onclick, it should open a popover, modal, or something to that affect, asking for confirmation of the delete.

The popover would have a second button which would actually run the delete action, and it would not intersect the button that opened the popover.

Deletes would require two clicks, making accidental deletion more unlikely, and giving users a moment of pause to ensure they really do want to delete it.

**Comment by psiemens** [comment]
I really like the idea of a `DeleteButton` that has confirmation built-in. I agree that it's too easy to delete things right now.

A quick solution would be to use [window.confirm](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm), which is what `react-router` uses to confirm navigation.

**Comment by joncppl** [comment]
I've implemented it with http://blueprintjs.com/docs/#core/components/alert

looks nice and has simple implementation.
