### ISSUE TITLE
User is asked for confirmation when creating a new section

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#614]
After clicking "save" on a section create page, the navigation confirmation dialog pops up. After clicking confirm, the section is still created, but the dialog shouldn't appear in the first place.

To fix, make sure the section create action is setting `ignoreLeaveHook` to true when dispatching the redirect.

**Comment by joncppl** [comment]
I'm unable to replicate the bug in develop:HEAD.
Wasn't it fixed by https://github.com/ubyssey/dispatch/pull/595/files ?
All calls to automatic create actions should have the ignoreLeaveHook, including sections.

**Comment by psiemens** [comment]
Ah, you're right. I can't reproduce it anymore either. Sorry about that -- closing the issue.
