### ISSUE TITLE
Content Editor doesn't escape html-like entities

### ISSUE THREAD

**Issue by joncppl** [ubyssey/dispatch#615]
Possible good but may be seen as weird behaviour:
Type `&copy` or other escape strings into the content editor and update. It turns into a ©. 

Definitely bad: HTML markup isn't escaped

Entering `<h1>Header</h1>`, updating, and it will stored as an h1 element. 
It will render in published page as an h1 element but not in the content editor, where it is uneditable.
However update once more and it goes back to a paragraph.

Anything that looks like an html tag gets swallowed.
eg. if a writer wanted to add  <> around something for stylistic reasons or because of the content of their article, it disappears!

**Comment by psiemens** [comment]
Yikes, this isn't good. Any ideas for how to fix it?

**Comment by joncppl** [comment]
probably a carefully placed call to an escapehtml function as the article content is updated.
I'm not sure where as I'm not super familiar with it.
