### ISSUE TITLE
EventSelectInput doesn't work properly

### ISSUE THREAD

**Issue by joncppl** [ubyssey/dispatch#619]
Not sure how I didn't notice this when it was first implemented, 

- Doesn't update the display as you make changes - addressed here https://github.com/ubyssey/dispatch/pull/618

If you select an event then update, it works. (It's sending just the id)
after the update, it doesn't work a second time if you don't change the event (even after reloading the page) since it's sending an entire event object.

**Comment by joncppl** [comment]
Probably I broke it by trying to fix the many case and made it too complicated.

**Comment by joncppl** [comment]
https://github.com/ubyssey/dispatch/pull/618/commits/ea699c0bfe3495bacbd8f4c85797b96c63ffca0f
fixes it for now.

**Comment by psiemens** [comment]
Not sure how I missed this as well 🤔 

I addressed the issue by adding a normalization step after fetching the widget fields. The change is here: #620
