### ISSUE TITLE
Background not extending to cover textfield in Safari

### ISSUE THREAD

**Issue by Axel-Jacobsen** [ubyssey/dispatch#626]
This is Safari
<img width="376" alt="screen shot 2017-07-17 at 2 49 10 pm" src="https://user-images.githubusercontent.com/20530172/28291556-d0f6754c-6aff-11e7-82e3-0aa3f4c35f8f.png">

This is Chrome
<img width="376" alt="screen shot 2017-07-17 at 2 48 49 pm" src="https://user-images.githubusercontent.com/20530172/28291557-d1085b4a-6aff-11e7-8d76-e6ebf032bac7.png">

**Comment by JamieRL** [comment]
appears to be fixed now.
