### ISSUE TITLE
Facebook import linebreaks

### ISSUE THREAD

**Issue by joncppl** [ubyssey/dispatch#637]
Linebreaks are lost in the facebook import process, It would be ideal if we could preserve them.

**Comment by joncppl** [comment]
Also deal with unicode/non-ascii characters

![image](https://user-images.githubusercontent.com/624196/28584097-51843f52-7120-11e7-8d7b-8373b60e2fbd.png)

**Comment by psiemens** [comment]
@joncppl is this resolved?

**Comment by joncppl** [comment]
Seems to be
