### ISSUE TITLE
Implement "header" format button

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#704]
![screen shot 2017-09-25 at 11 46 54 am](https://user-images.githubusercontent.com/2547035/30826136-3f15397a-a1ea-11e7-8910-0e5e664a463b.png)

The header button currently doesn't do anything. When clicked, it should apply the `'header-two'` block type.

Here's an example: https://github.com/ubyssey/dispatch/blob/develop/dispatch/static/manager/src/js/vendor/dispatch-editor/components/FormatPopover.js#L76

**Comment by i-ron-y** [comment]
So, I figured this out. Tried to push what I have upstream but I'm getting a permission denied message - do I need to be added to the dispatch team?

**Comment by psiemens** [comment]
Yep, added you to the dispatch team.
