### ISSUE TITLE
Bug: text editor area freezing after specific actions with some embeds.

### ISSUE THREAD

**Issue by i-ron-y** [ubyssey/dispatch#764]
**_How to reproduce:_**

**Video Embed:**
In the article editor, insert a video embed, provide a link, press Insert. Don't input anything in "Title", "Caption", or "Credit". Remove the embed.

**Gallery Embed:**
Select a gallery. Remove the embed.

**Widget Embed:**
Set a widget. Remove the embed.

At this point (for each of the embeds), the editor is now frozen and you can't click anywhere on it.

**Comment by Rowansdabomb** [comment]
I am unable to reproduce this on either my local machine or the live site

**Comment by i-ron-y** [comment]
Which browser are you using? I'm testing the current develop version on my local machine, in Chrome AND Firefox, and it's still doing that. It doesn't crash or anything - the text editor area just can't be clicked at all until you refresh the page.

**Comment by JamieRL** [comment]
Was able to replicate the issue on my local machine. Working on a fix

**Comment by JamieRL** [comment]
Fixed in pr #785
