### ISSUE TITLE
Nonetype error in WidgetField getitem

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/dispatch#772]
When new widget is added, "TypeError: 'NoneType' object has no attribute '__getitem__' " happens at /dispatch/theme/fields.py L319

@psiemens have a fix in mind

[GAE bug report](https://console.cloud.google.com/errors/CIGJuYb4g46nPQ?time=P1D&project=ubyssey-prd&authuser=0&organizationId=689563639437) + [GAE error line location](https://console.cloud.google.com/debug?repo=appengine:%3Fservice%3Ddefault%26version%3Dubyssey-v1-3-28&fp=%2Flib%2Fdispatch%2Ftheme%2Ffields.py&dlv=4&project=ubyssey-prd&authuser=0&organizationId=689563639437&app=GAE:default@ubyssey-v1-3-28&bp=56666c1695bda-d0e2-22321&cs=0) (need gae access)

**Comment by i-ron-y** [comment]
Hey, sorry for barging in... I'm not entirely sure if this is the same error that was popping up early on when I was dealing with the nested widget stuff, but if it is, I might have a simple fix for it. I'm going to make a PR just in case it's the same issue - but if it doesn't work, disregard it!

**Comment by i-ron-y** [comment]
Is this still an issue? The fix I've suggested has been merged recently as part of my work on the print issue widget (and widgets in general), so just wanted to check!

**Comment by psiemens** [comment]
@i-ron-y I _believe_ it's been fixed, but let me just confirm before we close the issue!
