### ISSUE TITLE
Prewview id error when updating Page

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/dispatch#776]
![image](https://user-images.githubusercontent.com/9669739/38645680-cb4339e2-3d99-11e8-8acf-7b9af066208d.png)

400 error when updating Contacts page

**Comment by JamieRL** [comment]
Fixed in version 0.4.5

**Comment by JamieRL** [comment]
Fix is still pending

**Comment by Rowansdabomb** [comment]
Fixed in version 0.4.7
