### ISSUE TITLE
Cannot remove featured image

### ISSUE THREAD

**Issue by Rowansdabomb** [ubyssey/dispatch#792]
Featured images can be added and updated, but not removed once added.

**Comment by i-ron-y** [comment]
Oh, I think this has been fixed already in my PR to allow articles to have video attachments - i had found this bug while working on it, and I fixed it in the meantime. The PR hasn’t been merged yet, but I think it’s been good to go for a while if you want to review it? Pull request #763

**Comment by Rowansdabomb** [comment]
Yea all the logic was there, but attachment.delete didn't immediately set featured_image to null. All good, the fix will be in the next release.

**Comment by Rowansdabomb** [comment]
Sorry, you did already fix it
