### ISSUE TITLE
Move ubyssey.ca specific data to settings

### ISSUE THREAD

**Issue by Rowansdabomb** [ubyssey/dispatch#834]
As dispatch begins to be forked by no ubyssey businesses, It is important that we separate ubyssey specific data from the dispatch.

example: google ad gpt tags in dispatch/modules/content/render.py

**Comment by keeganland** [comment]
Basically a hopeless task at this point. Code that is only intelligible to the main Ubyssey site is found all over this repo, with no one possessing a clear understanding of where. DNF
