### ISSUE TITLE
Articles filter glitch

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/dispatch#879]
One of the editors reported to us that the article filter doesn't work sometimes (In the example picture it should be filtered down to 60, but it says there's 98 instead). 

![screen shot 2018-10-05 at 1 37 14 pm](https://user-images.githubusercontent.com/9669739/46563038-1f52f900-c8b4-11e8-8872-b40cfc4f5502.png)

**Comment by psiemens** [comment]
This ended up being an issue with the way filters were being initialized. It's fixed in the latest release.
