### ISSUE TITLE
Add --help command to dispatch-admin

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/dispatch#883]
`dispatch-admin` command defined [here](https://github.com/ubyssey/dispatch/blob/develop/dispatch/bin/dispatch-admin) is currently missing a help command. Would be more user-friendly if the default command of `dispatch-admin` is help, or enable help command with `-h` and `--help` 

![image](https://user-images.githubusercontent.com/9669739/46780256-8582b600-ccd0-11e8-867d-8b8a145d1cc8.png)

[docopt](http://docopt.org/) can be used to format the help text

**Comment by theovasi** [comment]
I'd like to work on this.

**Comment by jumbosushi** [comment]
Awesome! You can follow the setup guide on code.ubyssey.ca to get started. Let me know if you need help

**Comment by EnthusiastDeveloper** [comment]
Have you considered using python's [argparse](https://docs.python.org/3/library/argparse.html) instead?
