### ISSUE TITLE
Search filter not working for Template

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/dispatch#891]
Current behaviour (Templates)
![search_error](https://user-images.githubusercontent.com/9669739/47673513-19c69700-db72-11e8-9cb7-8c92831fc7a9.gif)

Expected behaviour (Tag)
![expected](https://user-images.githubusercontent.com/9669739/47673586-44185480-db72-11e8-87c3-717b37865c80.gif)

We want the Template search filter to reduce the number of list rendered. `TagViewSet` is currently missing a filter method list the one in [TagViewSet](https://github.com/ubyssey/dispatch/blob/develop/dispatch/api/views.py#L280)

**Comment by Rowansdabomb** [comment]
fixed in #904
